### ISSUE TITLE
Crafting bug

### ISSUE THREAD

**Issue by drtakhs** [Vanhal/JACB#11]
When crafting multiple items on JACB and use right click to pick up all the items it usually gives you the wrong amount of items. Let me give you an example... 

The recipe for iron bars is  2 rows of 3 iron ingots per row (6 total) for 16 iron bars. When for example i place 2 rows of 6 iron ingots (first row: 2-2-2 second row: 2-2-2) i expect right clicking to craft all possible number of bars for a total of 32 iron bars just like the vanilla crafting table... instead i get only 24! This forces me to use multiple left clicks in order to not lose any items...

Reproduction rate 100%
MCversion : 1.7.10 forge
JACB version : JACB-1.7.10-1.0.4.jar

I have a JACB and a Vanilla crafting table... The vanilla ALWAYS gives me 32 bars while the JACB ALWAYS gives me the incorrect number of 24 bars... **This happens with most of the items!** 

Can you please look into it? It's pretty game-breaking.

If you need any other info, pictures or files please do not hesitate to ask me! I could help in anyway i can!

P.S : Sorry for my derpy English, it's obviously not my native language :P

**Comment by Vanhal** [comment]
Shift, Left click. But anyway it's fixed in 1.9

**Comment by slidingmike** [comment]
Is this unable to be fixed in the 1.7.10 version?

**Comment by Vanhal** [comment]
I put up a version that "should" fix it

**Comment by slidingmike** [comment]
From my testing, looks good. thanks for fixing it!
