### ISSUE TITLE
Q instead of clicking 

### ISSUE THREAD

**Issue by OJwithC** [Vanhal/JACB#2]
If you craft something in the JACB crafting table that yields more than one item (such as wood --> 4 planks) and press q instead of clicking or shift clicking, only one of the output will drop (1 plank instead of 4).

**Comment by Vanhal** [comment]
Wow, I have literally never done that... I'll see how I can actually fix that

**Comment by gigabit101** [comment]
This is a  Botaina Thing FYI

**Comment by Vanhal** [comment]
Fixed in 1.9.4
