### ISSUE TITLE
Consecutive crafting bug in JACB bench

### ISSUE THREAD

**Issue by vendris-DeVcoFTB** [Vanhal/JACB#6]
Hello,

Consecutive crafting seems bugged.

If you place 2 oak logs in the bench, and shift click them, you get 8 planks, as you should.

If you place 2 oak logs in the bench, and rightclick them them, you get 6 planks.

Works with slabs, and likely other items too.

Version tested: JACB-1.7.10-1.0.2

**Comment by Vanhal** [comment]
Fixed in 1.9
